#!/bin/sh
#
# Regenerate the TLS certificates used by the "tcps" test fixture.
#
# The certificates checked into this directory expire.  When they do,
# every test run against the "tcps" fixture fails with "certificate
# has expired".  Nothing in the build regenerates them, so a human has
# to run this script and commit the result.
#
# Usage:
#   ./generate.sh           regenerate the certificates
#   ./generate.sh --check   report expiry dates; exit nonzero if stale
#   ./generate.sh --dh      also regenerate the DH parameters
#
# Options -t DAYS and -s SECLEVEL override the certificate lifetime
# and the openssl security level; the defaults are almost certainly
# what you want.
#
# The script may be run from any directory.  See the "Test
# certificates" section of README.md.

set -e

# Locate ourselves, and the tree we live in.
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
top=$(CDPATH= cd -- "$here/../../../.." && pwd)
certtool=$top/libPlasma/c/ob-plasma-cert.sh

# Certificate lifetime, in days.  These are throwaway certificates for
# "localhost" which are checked into git, so there is nothing to be
# gained by making them short-lived -- a long lifetime just means
# nobody has to come back here for another decade.
lifetime=3650

# openssl security level 3, i.e. 3072-bit RSA keys and sha256
# digests.  Level 2 would be accepted too, but level 3 is what the
# certificates in git have always used.
# FIXME: revisit whether we can use security level 4 sometime soon
seclevel=3

# How far in advance of expiry --check starts complaining, in days.
horizon=30

# Size of the Diffie-Hellman parameters generated by --dh.
dhbits=2048

# The certificates, i.e. the files that carry an expiration date.
certs="ca-certificate.pem certificate-authorities.pem
       server-certificate.pem server-certificate-chain.pem
       client-certificate.pem client-certificate-chain.pem"

# Their private keys.  No expiration date, but they are replaced
# along with the certificates they belong to.
keys="ca-private-key.pem server-private-key.pem client-private-key.pem"

# Signing requests: intermediate files, deleted once we are done with
# them.  They are listed in .gitignore.
scratch="server.csr client.csr"

# Diffie-Hellman parameters, relative to the top of the tree.  These
# do not expire, which is why --dh is opt-in.  The two files are
# expected to have identical contents.
dhfiles="bld/cmake/fixtures/tcpo/dh-params.pem
         libPlasma/c++/tests-tp/dh-params.pem"

# Print the comment block at the top of this file.
usage() {
  sed -n '3,${/^#/!q; s/^#//; s/^ //; p;}' "$0"
}

abort() {
  echo "fatal error: $*" >&2
  exit 1
}

# Print each certificate's expiration date.  Returns nonzero if any of
# them has expired, or is about to.
do_check() {
  rc=0
  for f in $certs
  do
    if test ! -f "$here/$f"
    then
      echo "$f: MISSING"
      rc=1
    elif ! openssl x509 -in "$here/$f" -noout -checkend 0 > /dev/null
    then
      echo "$f: EXPIRED $(enddate "$f")"
      rc=1
    elif ! openssl x509 -in "$here/$f" -noout \
           -checkend $((horizon * 86400)) > /dev/null
    then
      echo "$f: EXPIRES WITHIN $horizon DAYS $(enddate "$f")"
      rc=1
    else
      echo "$f: ok, expires $(enddate "$f")"
    fi
  done
  return $rc
}

enddate() {
  openssl x509 -in "$here/$1" -noout -enddate | sed 's/^notAfter=//'
}

do_generate() {
  test -f "$certtool" || abort "cannot find $certtool"

  # ob-plasma-cert.sh writes its output to the current directory, and
  # refuses to overwrite an existing CA certificate.
  cd "$here"
  rm -f $certs $keys $scratch

  # These certificates carry no subjectAltName, so it is the server
  # certificate's common name that has to match the hostname the tests
  # connect to, which is always "localhost".  (Once a certificate does
  # have a subjectAltName, the common name stops being consulted at
  # all; see ob_ossl_cert_matches_host() in
  # libPlasma/c/ossl/ossl-validation.c.)  The client certificate's name
  # is not checked by anything.
  sh "$certtool" -t $lifetime -s $seclevel mkca
  sh "$certtool" -t $lifetime -s $seclevel mkserver localhost
  sh "$certtool" -t $lifetime -s $seclevel mkclient

  rm -f $scratch
}

do_dh() {
  tmp=$here/dh-params.pem.$$
  trap 'rm -f "$tmp"' EXIT
  echo "Generating $dhbits-bit DH parameters (this takes a while)..."
  openssl dhparam -out "$tmp" $dhbits
  for f in $dhfiles
  do
    cp "$tmp" "$top/$f"
  done
  rm -f "$tmp"
  trap - EXIT
}

check_only=no
want_dh=no
while test $# -gt 0
do
  case "$1" in
  --check) check_only=yes;;
  --dh)    want_dh=yes;;
  -t)      shift; lifetime=$1;;
  -s)      shift; seclevel=$1;;
  -h|--help) usage; exit 0;;
  *)       usage >&2; exit 1;;
  esac
  shift
done

if test $check_only = yes
then
  do_check || exit 1
  exit 0
fi

do_generate

if test $want_dh = yes
then
  do_dh
fi

echo
do_check
echo
echo "Regenerated.  Commit the result:"
echo "    git add $here"
